runtime: python27
api_version: 1
threadsafe: true
service: cloud-datastore-admin

libraries:
- name: webapp2
  version: "latest"

handlers:
- url: /cloud_datastore_export
  script: cloud_datastore_admin.app
  login: admin
